language: minimal
dist: xenial

services:
  - docker

cache:
  directories:
    - /home/travis/.local/share/img

env:
  global:
    - TRAVIS=true
  matrix:
    - IMAGE=core/admin
    - IMAGE=core/dovecot
    - IMAGE=core/nginx
    - IMAGE=core/none
    - IMAGE=core/postfix
    - IMAGE=optional/clamav
    - IMAGE=optional/postgresql
    - IMAGE=optional/radicale
    - IMAGE=optional/traefik-certdumper
    - IMAGE=services/fetchmail
    - IMAGE=services/rspamd
    - IMAGE=services/unbound
    - IMAGE=webmails/rainloop
    - IMAGE=webmails/roundcube

before_install:
- sudo bash scripts/setup-binfmt.sh
- bash scripts/cron-cache.sh
- mkdir ~/.local/share/img || true
- sudo chmod -R 777 ~/.local/share/img

script:
- bash build.sh

before_cache:
- sudo chmod -R 777 ~/.local/share/img
