language: minimal
dist: xenial

services:
  - docker

env:
  global:
    - TRAVIS=true
    secure: "rSiysV377Eua06to2PDP2R7YldM9LAhafi2oyv55vzXKIpAScf7fqpYB0tv6w763KGFFhUm77fqBujpLHsEo9x/QzS0rr4gT6OBJ3stc0yX3XdM6g3XdUmBRZgIl17K0d2Uf2K26TdqVkyl3xSPLMmml27EoskznjhD8nUthyWzP94bhzF/Bq96zetfMj/xgKpEuAInCrnoOsbaoypnhY+jZWdWakBElUYpzEBokgANYZoWdhbHWHRHst28IsgR1ZbPpNVL/F1qa6N38ZgczIXS6BtsUFuM2JLA3Z0bamxkph3hLrGanjV99KbC/wedKiQVMFrvw88B8UpK73agyfdhyyQgVpES1bmbkgysVRXvgf/8+eQQctbJtofEcPkq8qGnOs7vuNQhLcNsEyQQ7OKmkUG7X9NHaq3RSonWRi3fM2sXILp34SCeGA9+J1IcuceHsLpuYma049KptrgC9UJy0F9J/+idxHZJG3oNfLPDSkBDmLCEtAA7khu3dNguNsGPgABFOj90jwfn1ODMN2BQvLXJiHrYwwI4scaBWyP8UmDUyRtC5cJGepK0N1PfPFql97IgNrYMP7E59vDt9+1J/lc2iO9EANWrd80j6LKfVtdsRcNBy9fAmoHcRM5sknBKXk85zOL1ExiRmb2BJqaYId7GmoIihg9mzmVpGwLU="
  matrix:
    - IMAGE=core/admin
    - IMAGE=core/dovecot
    - IMAGE=core/nginx
    - IMAGE=core/none
    - IMAGE=core/postfix
    - IMAGE=optional/clamav
    - IMAGE=optional/postgresql
    - IMAGE=optional/radicale
    - IMAGE=optional/traefik-certdumper
    - IMAGE=services/fetchmail
    - IMAGE=services/rspamd
    - IMAGE=services/unbound
    - IMAGE=webmails/rainloop
    - IMAGE=webmails/roundcube

before_install:
- sudo bash scripts/setup-binfmt.sh
- bash scripts/cron-cache.sh
- mkdir ~/.local/share/img || true
- sudo chmod -R 777 ~/.local/share/img
- sudo chown -R root:root ~/.local/share/img

script:
- bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
