language: minimal
dist: xenial

services:
  - docker

env:
  global:
    - TRAVIS=true
    - secure: "QIpxYNLLBI0N3sjwXL9l3MCCLEhTWTUFQgeA5CjwBnbHd54eZUyYVqyAv/iCZtrABXryYv33xBwtCowxDF/y995XCg68ydZ335C9McTBJGX3/8J8MUdHg5MNSRoGAfp7m6JP4yiWqYfz8qwLDXvGabth3vTmELWkuRKIJ81OjijmDUSChDPiX/YH6dV3R8jrXsOYLF41fQa9toelifanXMAX9sMxbc6V+uTdnGgpX2gHGa/aGzWQvGNhlvZgRx5ar7zv7LTxTsjDbWLxw9ggaN4DRji0fAf3tjRvsY1P3Ay7ejfm4mUwVZ1CzVV6d2jAS3B2ml0ehWmWE8TCTrfSb/hEObM+DaZz8ZnrCtCKZI+FlqE3y2n3a+tKkRuGqgwvFpnJE4xJUhDXmbAIxktkKL/sZzZFNrNdXnTpQnJtwXgpCdUUM3w9iXiZaUAvtTKfYkaYYa6EqzpWcFLTsFJ2IM9x5XuZtSfmiQZALWQx5vh1MRK23IDFleVMT/+Toa4O5PpYF0Qexq0S4JwbBBYOibgPE7+/NQoAL1eyL1/fnvYAsOsNKcALztm1++2RgfXyJA2qi12AHO4nKY/RHT7zJYEG7VJAa23i1ptngsZmRDyG4ticuamqorO1O/ATmI5b9cwjUtCxiodbp/JdI8h1vsCrd/PLNPzmQ9NKZ91KRaQ="
  matrix:
    - IMAGE=core/admin
    - IMAGE=core/dovecot
    - IMAGE=core/nginx
    - IMAGE=core/none
    - IMAGE=core/postfix
    - IMAGE=optional/clamav
    - IMAGE=optional/postgresql
    - IMAGE=optional/radicale
    - IMAGE=optional/traefik-certdumper
    - IMAGE=services/fetchmail
    - IMAGE=services/rspamd
    - IMAGE=services/unbound
    - IMAGE=webmails/rainloop
    - IMAGE=webmails/roundcube

before_install:
- sudo bash scripts/setup-binfmt.sh
- bash scripts/cron-cache.sh
- mkdir ~/.local/share/img || true
- sudo chmod -R 777 ~/.local/share/img
- sudo chown -R root:root ~/.local/share/img

script:
- bash build.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
